source 'http://rubygems.org'

gem 'sinatra'
gem 'capybara'
gem 'rspec'
gem 'rspec-sinatra'
gem 'rack'
gem 'json'
gem 'data_mapper'
gem 'database_cleaner'
gem 'dm-postgres-adapter'
gem 'sinatra-contrib'
